---
- name: db
  hosts: db
  gather_facts: false
  vars_files:
    - vars/windows.yml

  roles:
    - { role: mdb, tags: mdb }
    - { role: users, tags: users }
    - { role: dbusers, tags: dbusers }
    - { role: sqlscripts, tags: sqlscripts } # another is mpegdb
    - { role: ntp, tags: ntp }
    - { role: reboot, tags: reboot }
    - { role: mpegdb, tags: mpegdb }
    - { role: populate_hosts, tags: populate_hosts }
    - { role: spot_install, tags: spot_install }
    - { role: automation_tests, tags: automation_tests }
