---
- name: db
  hosts: db
  gather_facts: false
  vars_files:
    - vars/windows.yml

  roles:
    - { role: mdb, tags: mdb }
    - { role: users, tags: users }
    - { role: dbusers, tags: dbusers }
    - { role: sqlscripts, tags: sqlscripts } # another is mpegdb
    - { role: ntp, tags: ntp }
    - { role: reboot, tags: reboot }
    - { role: mpegdb, tags: mpegdb }
    - { role: populate_hosts, tags: populate_hosts }
    - { role: spot_install, tags: spot_install }

- name: mvl
  hosts: mvl
  gather_facts: false
  vars_files:
    - vars/windows.yml

  roles:
    - { role: users, tags: users }
    - { role: mvl, tags: mvl }
    - { role: ntp, tags: ntp }
    - { role: populate_hosts, tags: populate_hosts }
      #- { role: reboot, tags: reboot }

- name: tss
  hosts: tss
  gather_facts: false
  vars_files:
    - vars/windows.yml

  roles:
    - { role: users, tags: users }
    - { role: tss, tags: tss }
    - { role: ntp, tags: ntp }
    - { role: populate_hosts, tags: populate_hosts }
      #- { role: reboot, tags: reboot }

- name: tsi
  hosts: tsi
  gather_facts: false
  vars_files:
    - vars/windows.yml

  roles:
    - { role: users, tags: users }
    - { role: ntp, tags: ntp }
    - { role: populate_hosts, tags: populate_hosts }
    - { role: reboot, tags: reboot }
