---
- name: db
  hosts: db
  gather_facts: false
  vars_files:
    - vars/windows.yml
    - vars/mdb.yml
  
  roles:
    - { role: mdb, tags: mdb }
    - { role: users, tags: users }
    - { role: sqlscripts, tags: sqlscripts }
    - { role: ntp, tags: ntp }
    - { role: reboot, tags: reboot }
    - { role: mpegdb, tags: mpegdb }
