---
- name: Add FullControl AccessRule
  win_acl:
    path: C:\Program Files\Microsoft SQL Server
    user: "{{ item }}"
    rights: FullControl
    type: allow
    state: present
    #inherit: ContainerInherit, ObjectInherit
    propagation: 'None'
    become: yes
  with_items:
  - Administrator
  - Administrators
  - Spot Administrators
  - Spot Services
    
- name: create folder d_data
  win_file:
    path: "{{ item }}"
    type: directory
  with_items:
    - D:\sql
    - D:\sql\data

- name: copy create_mpeg.sql file
  win_get_url:
    url: "{{ mirror }}/sql/create_mpeg.sql"
    dest: '{{ destdir }}'
    force: no

- name: Execute the SQL Script create_mpeg.sql
  win_command: sqlcmd -S {{ dbname }} -i C:\temp\create_mpeg.sql -o C:\temp\create_mpeg.txt

- name: copy SPOT53_populate_zone_support.sql file
  win_get_url:
    url: "{{ mirror }}/sql/SPOT53_populate_zone_support.sql"
    dest: '{{ destdir }}'
    force: no
  tags: populatezonesql

- name: Execute the SQL Script SPOT53_populate_zone_support.sql
  win_command: sqlcmd -S {{ dbname }} -i C:\temp\SPOT53_populate_zone_support.sql -o C:\temp\SPOT53_populate_zone_support.txt
