---
- name: create folder
  win_file:
    #path: c:\program files\microsoft sql server\mssql\data
    path: C:\Program Files\Microsoft SQL Server\mssql\data
    type: directory

- name: copy create_mpeg.sql file
  win_get_url:
    url: "{{ mirror }}/sql/create_mpeg.sql"
    dest: '{{ destdir }}'
    force: no

- name: Execute the SQL Script to Add Users to the SQL Server
  win_command: sqlcmd -S SPOTDB2016 -i C:\temp\create_mpeg.sql
