---
# create reboot_lock to avoid reboot in reboot role
- name: Create reboot_lock
  win_file:
    path: C:\temp\reboot_lock.txt
    state: touch
  changed_when: no

- name: Add FullControl AccessRule
  win_acl:
    path: C:\Program Files\Microsoft SQL Server
    user: "{{ item }}"
    rights: FullControl
    type: allow
    state: present
    #inherit: ContainerInherit, ObjectInherit
    propagation: 'None'
    become: yes
  with_items:
  - Administrator
  - Administrators
  - Spot Administrators
  - Spot Services

- name: create folder d_data
  win_file:
    path: "{{ item }}"
    type: directory
    recurse: yes
  with_items:
    - D:\sql
    - D:\sql\data

- name: copy create_mpeg.sql file
  win_template:
    src: create_mpeg.sql
    dest: '{{ destdir }}'
    force: no

- name: Check for create_mpeg.txt output
  win_stat:
    path: C:\temp\create_mpeg.txt
    get_checksum: yes
  register: create_mpeg

- name: Execute the SQL Script create_mpeg.sql
  win_command: sqlcmd -S {{ dbname }} -i C:\temp\create_mpeg.sql -o C:\temp\create_mpeg.txt
  when: (not create_mpeg.stat.exists) or (create_mpeg.stat.exists and create_mpeg.stat.checksum != "554633c3309ee945b9b952282abfa7c4b94465ba")

- name: copy SPOT53_populate_zone_support.sql file
  win_get_url:
    url: "{{ mirror }}/sql/SPOT53_populate_zone_support.sql"
    dest: '{{ destdir }}'
    force: no
  tags: populatezonesql

- name: Check for SPOT53_populate_zone_support.txt output
  win_stat:
    path: C:\temp\SPOT53_populate_zone_support.txt
    get_checksum: yes
  register: populate_zone_support

- name: Execute the SQL Script SPOT53_populate_zone_support.sql
  win_command: sqlcmd -I -S {{ dbname }} -i C:\temp\SPOT53_populate_zone_support.sql -o C:\temp\SPOT53_populate_zone_support.txt
  when: (not populate_zone_support.stat.exists) or (populate_zone_support.stat.exists and populate_zone_support.stat.checksum != "2e430b6a6d88ffd3f76e1b529e9c6a65f1f3a47a")
  tags: populatezonesql
