---
- name: Modify Log On as a Service Policy in User Rights Assignment Local Security Policy Settings
  win_user_right:
    name: SeServiceLogonRight
    users: SPOTDB2016\Spot Services
    action: add
