---
- name: Check if host is part of domain
  win_command: wmic computersystem get domain
  register: domain
  changed_when: no

- name: Run gpupdate
  win_command: gpupdate /force
  when: not "WORKGROUP" in domain.stdout

- name: Check if reboot_lock exists
  win_stat:
    path: '{{ destdir }}\reboot_lock.txt'
  register: reboot_lock

- name: Reboot
  win_reboot:
    reboot_timeout: 3600
  when: not reboot_lock.stat.exists
