---
- name: copy sql_configuration.sql file
  win_get_url:
    url: "{{ mirror }}/sql_configuration.sql"
    dest: '{{ destdir }}'
    force: no

- name: Apply SQL configuration
  win_command: sqlcmd -S SPOTDB2016 -i C:\temp\sql_configuration.sql 

- name: copy sql_add_users.sql file
  win_get_url:
    url: "{{ mirror }}/sql_add_users.sql"
    dest: '{{ destdir }}'
    force: no

- name: Execute the SQL Script to Add Users to the SQL Server
  win_command: sqlcmd -S SPOTDB2016 -i C:\temp\sql_add_users.sql

  # Change MSSQLServer and SQLServer Agent Accounts to Use Local Account

- name: Stop SQL Server Agent
  win_service:
    name: SQLSERVERAGENT
    username: .\LocalScsetup
    password: "{{ sapwd }}"
    state: stopped
    start_mode: auto
  register: sqlserveragent

- name: Restart MSSQLSERVER service
  win_service:
    name: MSSQLSERVER
    state: restarted
    username: .\LocalScsetup
    password: "CdCi2010"
    #password: "{{ sapwd }}"
    start_mode: auto
  register: mssqlserver

- name: Start SQL Server Agent
  win_service:
    name: SQLSERVERAGENT
    username: .\LocalScsetup
    password: "{{ sapwd }}"
    state: started
    start_mode: auto
  register: sqlserveragent
