---
- name: copy sql_configuration.sql file
  win_get_url:
    url: "{{ mirror }}/sql/sql_configuration.sql"
    dest: '{{ destdir }}'
    force: no

- name: Check for sql_configuration.txt output
  win_stat:
    path: C:\temp\sql_configuration.txt
    get_checksum: yes
  register: sql_configuration

- name: Apply SQL sql_configuration.sql file
  win_command: sqlcmd -S {{ dbname }} -i C:\temp\sql_configuration.sql -o C:\temp\sql_configuration.txt
  when: (not sql_configuration.stat.exists) or (sql_configuration.stat.exists and sql_configuration.stat.checksum != "5b262ef633b120c258336c686f0c653e290d3521")

- name: copy sql_add_users.sql file
  win_get_url:
    url: "{{ mirror }}/sql/sql_add_users.sql"
    dest: '{{ destdir }}'
    force: no

- name: Check for sql_add_users.txt output
  win_stat:
    path: C:\temp\sql_add_users.txt
    get_checksum: yes
  register: sql_add_users

- name: Execute the SQL Script to Add Users to the SQL Server
  win_command: sqlcmd -S {{ dbname }} -i C:\temp\sql_add_users.sql -o C:\temp\sql_add_users.txt
  when: not sql_add_users.stat.exists

  # Change MSSQLServer and SQLServer Agent Accounts to Use Local Account

- name: Obtain information about a registry key property
  win_reg_stat:
    path: HKLM:\SOFTWARE\WOW6432Node\SeaChange\CDCI\Setup\About
    name: Version
  register: reg_spot_version

- name: Stop SQL Server Agent
  win_service:
    name: SQLSERVERAGENT
    username: .\LocalScsetup
    password: "{{ sapwd }}"
    state: stopped
    start_mode: auto
  register: sqlserveragent
  when: not reg_spot_version.exists

- name: Restart MSSQLSERVER service
  win_service:
    name: MSSQLSERVER
    state: restarted
    username: .\LocalScsetup
    password: "{{ sapwd }}"
    start_mode: auto
  register: mssqlserver
  when: not reg_spot_version.exists

- name: Start SQL Server Agent
  win_service:
    name: SQLSERVERAGENT
    username: .\LocalScsetup
    password: "{{ sapwd }}"
    state: started
    start_mode: auto
  register: sqlserveragent
  when: not reg_spot_version.exists
