---
- name: Create groups
  win_group:
    name: "{{ item }}"
    state: present
  with_items:
    - Administrators
    - Spot Administrators
    - Spot Services
    - Spot View Only

- name: Ensure users are present
  win_user:
    name: "{{ item }}"
    password: Cdci2010
    state: present
    password_never_expires: yes
    groups: Administrators
  with_items:
    - LocalScsetup
    - LocalSpotServices
    - LocalViewOnlyUser
