---
- name: Create groups
  win_group:
    name: "{{ item }}"
    state: present
  with_items:
    - Administrators
    - Spot Administrators
    - Spot Services
    - Spot View Only

- name: Ensure users are present
  win_user:
    name: "{{ item }}"
    password: Cdci2010
    state: present
    password_never_expires: yes
    groups: Administrators
  with_items:
    - LocalScsetup
    - LocalSpotServices
    - LocalViewOnlyUser

#- name: Add Administrator into Spot Administrators group
#  win_user:
#    name: Administrator
#    state: present
#    groups: Spot Administrators

- name: Add Users into Spot Services group
  win_user:
    name: "{{ item }}"
    state: present
    groups: Spot Services
  with_items:
    - LocalScsetup
    - LocalSpotServices

- name: Add LocalViewOnlyUser into Spot View Only group
  win_user:
    name: LocalViewOnlyUser
    state: present
    groups: Spot View Only

- name: Modify Log On as a Service Policy in User Rights Assignment Local Security Policy Settings
  win_user_right:
    name: SeServiceLogonRight
    users: SPOTDB2016\Spot Services
    action: add
