---
- name: Change the hostname
  win_hostname:
    name: "{{ mdb_hostname }}"
  register: hostname

- name: Reboot if hostname has changed
  win_reboot:
    reboot_timeout: 3600
  when: hostname.changed

- name: Create directories
  win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - '{{ destdir }}'
    - C:\Program Files (x86)\Microsoft SQL Server\DReplayClient\ResultDir
    - C:\Program Files (x86)\Microsoft SQL Server\DReplayClient\WorkingDir

- name: Check for mssqlserver service
  win_service:
    name: MSSQLSERVER
  register: mssqlserver_service

- name: Copy SQLServer2016 ISO file
  win_get_url:
    url: "{{ mirror }}/SQLServer2016SP1-FullSlipstream-x64-ENU.iso"
    dest: '{{ destdir }}'
    force: no
  when: not mssqlserver_service.exists

- name: Copy answer template
  win_template:
    src: ConfigurationFile.ini
    dest: '{{ destdir }}'
    force: yes
  when: not mssqlserver_service.exists

- name: Mount ISO
  win_disk_image:
    image_path: '{{ destdir }}\SQLServer2016SP1-FullSlipstream-x64-ENU.iso'
    state: present
  register: image_out
  when: not mssqlserver_service.exists

- name: Install SQL Server 2016
  win_package:
    path: '{{ image_out.mount_path }}\setup.exe'
    state: present
    arguments: /SAPWD="{{ sapwd }}" /ConfigurationFile="{{ destdir }}\ConfigurationFile.ini"
    product_id: '{16F3645F-1343-4462-92DC-9AE66A2E68A3}'
  when: not mssqlserver_service.exists

- name: Unmount ISO
  win_disk_image:
    image_path: '{{ destdir }}\SQLServer2016SP1-FullSlipstream-x64-ENU.iso'
    state: absent
  when: not image_out is failed

- name: Copy Microsoft SQL Server Management Studio file
  win_get_url:
    url: "{{ mirror }}/SSMS-Setup-ENU.exe"
    dest: '{{ destdir }}'
    force: no

- name: Install Microsoft SQL Server Management Studio
  win_package:
    path: '{{ destdir }}\SSMS-Setup-ENU.exe'
    state: present
    arguments: /install /quiet /norestart
    product_id: '{1B8CFC46-1F08-4DA7-9FEA-E1F523FBD67F}'
