---
  - name: create temp dir
    win_file:
      path: '{{ destdir }}'
      state: directory

  - name: create dreplay result dir
    win_file:
      path: C:\Program Files (x86)\Microsoft SQL Server\DReplayClient\ResultDir
      state: directory

  - name: create dreplay working dir
    win_file:
      path: C:\Program Files (x86)\Microsoft SQL Server\DReplayClient\WorkingDir
      state: directory

  - name: copy iso file
    win_get_url:
      url: "{{ mirror }}/SQLServer2016SP1-FullSlipstream-x64-ENU.iso"
      dest: '{{ destdir }}'
      force: no

  - name: copy answer file
    win_get_url:
      url: "{{ mirror }}/ConfigurationFile.ini"
      dest: '{{ destdir }}'
      force: no

  - name: Check if MSSQL folder exists
    win_stat:
      path: C:\Program Files\Microsoft SQL Server
    register: folder
    ignore_errors: True

  - name: Mount ISO
    win_disk_image:
      image_path: '{{ destdir }}\SQLServer2016SP1-FullSlipstream-x64-ENU.iso'
      state: present
    register: image_out
    when: not folder.stat.isdir

  - name: install SQL server
    win_package:
      path: '{{ image_out.mount_path }}\setup.exe'
      state: present 
      arguments: /SAPWD="{{ sapwd }}" /ConfigurationFile="{{ destdir }}\ConfigurationFile.ini"
      product_id: '{16F3645F-1343-4462-92DC-9AE66A2E68A3}'
    when: not folder.stat.isdir

  - name: Unmount ISO
    win_disk_image:
      image_path: '{{ destdir }}\SQLServer2016SP1-FullSlipstream-x64-ENU.iso'
      state: absent

  - name: copy MSSM file
    win_get_url:
      url: "{{ mirror }}/SSMS-Setup-ENU.exe"
      dest: '{{ destdir }}'
      force: no

  - name: install Microsoft SQL Server Management Studio
    win_package:
      path: '{{ destdir }}\SSMS-Setup-ENU.exe'
      state: present 
      #arguments: /install /quiet /norestart
      product_id: '{1B8CFC46-1F08-4DA7-9FEA-E1F523FBD67F}'
      #register: mssmsetup

