---
# tasks file for spot_install
- name: Obtain information about a registry key property
  win_reg_stat:
    path: HKLM:\SOFTWARE\WOW6432Node\SeaChange\CDCI\Setup\About
    name: Version
  register: reg_spot_version

# http://192.168.197.213/Spot/1081/Kit/SPOT_SOFTWARE_v7.5.0.4.iso
- name: Copy SPOT iso file
  win_get_url:
    url: "{{ mirror_spot }}/{{ build_spot }}/Kit/{{ spot_iso }}"
    dest: '{{ destdir }}'
    force: yes
  when: not reg_spot_version.exists

- name: Mount SPOT ISO
  win_disk_image:
    image_path: '{{ destdir }}\{{ spot_iso}}'
    state: present
  register: image_out
  when: not reg_spot_version.exists

# mdb only for now
- name: Copy {{ spot_function }}.json
  win_template:
    src: templates/{{ spot_function }}.json
    dest: '{{ destdir }}'
    force: no
  when: not reg_spot_version.exists

- name: Run SPOT setup.exe copy distribution folder
  win_shell: '{{ image_out.mount_path }}\spot\Setup\setup.exe -distribute "{{ dbname }}"'
  args:
    chdir: '{{ image_out.mount_path }}\spot\Setup'
  when: not reg_spot_version.exists

# paths were changed from MSSQL10 to MSSQL13 C:\cdci\distribution\SQL\Scripts\rep_mstr_2008.sql
- name: Overwrite rep_mstr_2008.sql script
  win_copy:
    src: files/rep_mstr_2008.sql
    dest: C:\cdci\distribution\SQL\Scripts\
    force: yes
    remote_src: no
  when: not reg_spot_version.exists

- name: Run SPOT setup.exe with answer file
  win_shell: '{{ image_out.mount_path }}\spot\Setup\setup.exe -answer="{{ destdir }}\{{ spot_function }}.json"'
  args:
    chdir: '{{ image_out.mount_path }}\spot\Setup'
  when: not reg_spot_version.exists

# reboot goes here
- name: Wait for the first reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: not reg_spot_version.exists

- name: Wait for the second reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 90
    timeout: 300
  when: not reg_spot_version.exists
